# Generated by Django 6.1.1 on 2026-09-12 08:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetryPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('initial_delay_seconds', models.PositiveIntegerField(default=5)),
                ('backoff_multiplier', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('max_delay_seconds', models.PositiveIntegerField(default=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'job_retry_policies',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(max_length=100)),
                ('workload_class', models.CharField(choices=[('LATENCY_SENSITIVE', 'Latency Sensitive'), ('IO_BOUND', 'IO Bound'), ('CPU_BOUND', 'CPU Bound'), ('AI_HEAVY', 'AI Heavy')], default='IO_BOUND', max_length=32)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('QUEUED', 'Queued'), ('EXECUTING', 'Executing'), ('RETRY_WAIT', 'Retry Wait'), ('CANCEL_REQUESTED', 'Cancel Requested'), ('SUCCEEDED', 'Succeeded'), ('FAILED_FINAL', 'Failed Final'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=32)),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Highest'), (2, 'High'), (3, 'Normal'), (4, 'Low'), (5, 'Lowest')], default=3)),
                ('payload', models.JSONField(default=dict)),
                ('result', models.JSONField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True)),
                ('available_at', models.DateTimeField()),
                ('ready_since', models.DateTimeField()),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('last_error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('last_error_message', models.TextField(blank=True, null=True)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='tenants.tenant')),
                ('retry_policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='jobs.retrypolicy')),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='TenantSchedulerState',
            fields=[
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='scheduler_state', serialize=False, to='tenants.tenant')),
                ('active_reservations', models.PositiveSmallIntegerField(default=0)),
                ('has_ready_work', models.BooleanField(default=False)),
                ('highest_ready_priority', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('next_ready_at', models.DateTimeField(blank=True, null=True)),
                ('last_dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenant_scheduler_state',
                'indexes': [models.Index(fields=['has_ready_work', 'highest_ready_priority', 'last_dispatched_at'], name='idx_scheduler_ready'), models.Index(fields=['next_ready_at'], name='idx_scheduler_next_ready')],
            },
        ),
        migrations.CreateModel(
            name='DeadLetterJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('RETRIES_EXHAUSTED', 'Retries Exhausted'), ('PERMANENT_FAILURE', 'Permanent Failure'), ('HANDLER_NOT_FOUND', 'Handler Not Found'), ('INVALID_CONFIGURATION', 'Invalid Configuration'), ('POISON_JOB', 'Poison Job')], max_length=64)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('REPLAYED', 'Replayed'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=16)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('last_attempt_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replayed_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dead_letter_jobs', to='tenants.tenant')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dead_letter', to='jobs.job')),
                ('replayed_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replayed_from_dead_letters', to='jobs.job')),
            ],
            options={
                'db_table': 'dead_letter_jobs',
                'indexes': [models.Index(fields=['tenant', 'status', 'created_at'], name='idx_dlq_tenant_status'), models.Index(fields=['status', 'created_at'], name='idx_dlq_status_created')],
            },
        ),
        migrations.CreateModel(
            name='JobAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('TIMED_OUT', 'Timed Out'), ('ABANDONED', 'Abandoned'), ('CANCELLED', 'Cancelled')], default='RUNNING', max_length=32)),
                ('worker_id', models.CharField(blank=True, max_length=255, null=True)),
                ('failure_type', models.CharField(blank=True, choices=[('TRANSIENT', 'Transient'), ('PERMANENT', 'Permanent'), ('INFRASTRUCTURE', 'Infrastructure'), ('TIMEOUT', 'Timeout'), ('UNKNOWN', 'Unknown')], max_length=32, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='jobs.job')),
            ],
            options={
                'db_table': 'job_attempts',
                'indexes': [models.Index(fields=['job', 'status'], name='idx_attempt_job_status'), models.Index(fields=['status', 'lease_expires_at'], name='idx_attempt_lease')],
                'constraints': [models.UniqueConstraint(fields=('job', 'attempt_number'), name='uq_job_attempt_number')],
            },
        ),
        migrations.CreateModel(
            name='JobExecutionReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lease_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='execution_reservation', to='jobs.job')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_reservations', to='tenants.tenant')),
            ],
            options={
                'db_table': 'job_execution_reservations',
                'indexes': [models.Index(fields=['tenant', 'expires_at'], name='idx_reservation_tenant_expiry')],
            },
        ),
        migrations.CreateModel(
            name='JobOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('DISPATCH_JOB', 'Dispatch Job')], default='DISPATCH_JOB', max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PUBLISHED', 'Published')], default='PENDING', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('publish_attempts', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox_events', to='jobs.job')),
            ],
            options={
                'db_table': 'job_outbox',
                'indexes': [models.Index(fields=['status', 'available_at', 'created_at'], name='idx_outbox_pending'), models.Index(fields=['job', 'status'], name='idx_outbox_job_status')],
            },
        ),
        migrations.CreateModel(
            name='JobOverlapLock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('TENANT', 'Tenant'), ('GLOBAL', 'Global')], default='TENANT', max_length=16)),
                ('resource_key', models.CharField(max_length=255)),
                ('lease_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overlap_locks', to='jobs.job')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_overlap_locks', to='tenants.tenant')),
            ],
            options={
                'db_table': 'job_overlap_locks',
                'indexes': [models.Index(fields=['tenant', 'resource_key'], name='idx_overlap_tenant_resource'), models.Index(fields=['expires_at'], name='idx_overlap_expiry')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('scope', 'TENANT')), fields=('tenant', 'resource_key'), name='uq_tenant_overlap_resource'), models.UniqueConstraint(condition=models.Q(('scope', 'GLOBAL')), fields=('resource_key',), name='uq_global_overlap_resource')],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['tenant', 'status', 'priority', 'available_at'], name='idx_job_dispatch_lookup'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'available_at'], name='idx_job_ready_lookup'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('tenant', 'idempotency_key'), name='uq_job_tenant_idempotency_key'),
        ),
    ]
