# Generated by Django 6.1.1 on 2026-09-12 11:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('REPORTS', 'Reports'), ('DATA_PROCESSING', 'Data Processing'), ('SYNCHRONIZATION', 'Synchronization'), ('AI_PROCESSING', 'AI Processing'), ('NOTIFICATION', 'Notification')], max_length=50)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('QUEUED', 'Queued'), ('EXECUTING', 'Executing'), ('RETRY_WAIT', 'Retry Wait'), ('CANCEL_REQUESTED', 'Cancel Requested'), ('SUCCEEDED', 'Succeeded'), ('FAILED_FINAL', 'Failed Final'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=32)),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Highest'), (2, 'High'), (3, 'Normal'), (4, 'Low'), (5, 'Lowest')], default=3)),
                ('payload', models.JSONField(default=dict, help_text='Arbitrary JSON payload parameters passed to the job handler.')),
                ('result', models.JSONField(blank=True, help_text='Output JSON returned by the job handler upon success.', null=True)),
                ('idempotency_key', models.CharField(blank=True, default=uuid.uuid4, max_length=255, null=True)),
                ('available_at', models.DateTimeField(help_text='Earliest time this job can be executed (used for delayed jobs or retry backoff).')),
                ('ready_since', models.DateTimeField(help_text='Timestamp when job became ready (used for fair FIFO dispatching within the same priority).')),
                ('attempt_count', models.PositiveSmallIntegerField(default=0, help_text='Number of execution attempts executed so far.')),
                ('last_error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('last_error_message', models.TextField(blank=True, null=True)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='DeadLetterJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('RETRIES_EXHAUSTED', 'Retries Exhausted'), ('PERMANENT_FAILURE', 'Permanent Failure'), ('HANDLER_NOT_FOUND', 'Handler Not Found'), ('INVALID_CONFIGURATION', 'Invalid Configuration'), ('POISON_JOB', 'Poison Job')], max_length=64)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('REPLAYED', 'Replayed'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=16)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('last_attempt_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Diagnostic context captured at the moment of failure.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replayed_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dead_letter_jobs', to='tenants.tenant')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dead_letter', to='jobs.job')),
                ('replayed_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replayed_from_dead_letters', to='jobs.job')),
            ],
            options={
                'db_table': 'dead_letter_jobs',
            },
        ),
        migrations.CreateModel(
            name='JobAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('TIMED_OUT', 'Timed Out'), ('ABANDONED', 'Abandoned'), ('CANCELLED', 'Cancelled')], default='RUNNING', max_length=32)),
                ('worker_id', models.CharField(blank=True, max_length=255, null=True)),
                ('failure_type', models.CharField(blank=True, choices=[('TRANSIENT', 'Transient'), ('PERMANENT', 'Permanent'), ('INFRASTRUCTURE', 'Infrastructure'), ('TIMEOUT', 'Timeout'), ('UNKNOWN', 'Unknown')], max_length=32, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('traceback', models.TextField(blank=True, help_text='Full Python exception traceback for debugging.', null=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, help_text='Last timestamp worker verified it was actively working on this attempt.', null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, help_text='Worker lease expiry time. If now() > lease_expires_at, worker is deemed dead.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='jobs.job')),
            ],
            options={
                'db_table': 'job_attempts',
            },
        ),
        migrations.CreateModel(
            name='JobExecutionReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lease_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField(help_text='Timestamp when this reservation expires if not refreshed by worker heartbeat.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='execution_reservation', to='jobs.job')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_reservations', to='tenants.tenant')),
            ],
            options={
                'db_table': 'job_execution_reservations',
            },
        ),
        migrations.CreateModel(
            name='JobOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('DISPATCH_JOB', 'Dispatch Job')], default='DISPATCH_JOB', max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PUBLISHED', 'Published')], default='PENDING', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('publish_attempts', models.PositiveIntegerField(default=0, help_text='Number of attempts made by the outbox publisher to send to Redis.')),
                ('available_at', models.DateTimeField(help_text='Earliest time this event should be published.')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox_events', to='jobs.job')),
            ],
            options={
                'db_table': 'job_outbox',
            },
        ),
        migrations.CreateModel(
            name='JobOverlapLock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('TENANT', 'Tenant'), ('GLOBAL', 'Global')], default='TENANT', max_length=16)),
                ('resource_key', models.CharField(help_text='Unique resource identifier that cannot be processed concurrently.', max_length=255)),
                ('lease_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField(help_text='Safety expiry timestamp after which this lock is automatically considered invalid.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overlap_locks', to='jobs.job')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_overlap_locks', to='tenants.tenant')),
            ],
            options={
                'db_table': 'job_overlap_locks',
            },
        ),
        migrations.CreateModel(
            name='TenantSchedulerState',
            fields=[
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='scheduler_state', serialize=False, to='tenants.tenant')),
                ('active_reservations', models.PositiveSmallIntegerField(default=0, help_text='Current number of concurrently executing jobs for this tenant.')),
                ('has_ready_work', models.BooleanField(default=False, help_text='True if there are jobs in WAITING status ready to be executed for this tenant.')),
                ('highest_ready_priority', models.PositiveSmallIntegerField(blank=True, help_text='Highest priority value (1=Highest, 5=Lowest) among ready waiting jobs.', null=True)),
                ('next_ready_at', models.DateTimeField(blank=True, help_text='Earliest available_at timestamp among all waiting jobs for this tenant.', null=True)),
                ('last_dispatched_at', models.DateTimeField(blank=True, help_text='Timestamp of the most recent job dispatch (used for fair round-robin scheduling).', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenant_scheduler_state',
                'indexes': [models.Index(fields=['has_ready_work', 'highest_ready_priority', 'last_dispatched_at'], name='idx_scheduler_ready'), models.Index(fields=['next_ready_at'], name='idx_scheduler_next_ready')],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['tenant', 'status', 'priority', 'available_at'], name='idx_job_dispatch_lookup'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'available_at'], name='idx_job_ready_lookup'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('tenant', 'idempotency_key'), name='uq_job_tenant_idempotency_key'),
        ),
        migrations.AddIndex(
            model_name='deadletterjob',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='idx_dlq_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='deadletterjob',
            index=models.Index(fields=['status', 'created_at'], name='idx_dlq_status_created'),
        ),
        migrations.AddIndex(
            model_name='jobattempt',
            index=models.Index(fields=['job', 'status'], name='idx_attempt_job_status'),
        ),
        migrations.AddIndex(
            model_name='jobattempt',
            index=models.Index(fields=['status', 'lease_expires_at'], name='idx_attempt_lease'),
        ),
        migrations.AddConstraint(
            model_name='jobattempt',
            constraint=models.UniqueConstraint(fields=('job', 'attempt_number'), name='uq_job_attempt_number'),
        ),
        migrations.AddIndex(
            model_name='jobexecutionreservation',
            index=models.Index(fields=['tenant', 'expires_at'], name='idx_reservation_tenant_expiry'),
        ),
        migrations.AddIndex(
            model_name='joboutbox',
            index=models.Index(fields=['status', 'available_at', 'created_at'], name='idx_outbox_pending'),
        ),
        migrations.AddIndex(
            model_name='joboutbox',
            index=models.Index(fields=['job', 'status'], name='idx_outbox_job_status'),
        ),
        migrations.AddIndex(
            model_name='joboverlaplock',
            index=models.Index(fields=['tenant', 'resource_key'], name='idx_overlap_tenant_resource'),
        ),
        migrations.AddIndex(
            model_name='joboverlaplock',
            index=models.Index(fields=['expires_at'], name='idx_overlap_expiry'),
        ),
        migrations.AddConstraint(
            model_name='joboverlaplock',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'TENANT')), fields=('tenant', 'resource_key'), name='uq_tenant_overlap_resource'),
        ),
        migrations.AddConstraint(
            model_name='joboverlaplock',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'GLOBAL')), fields=('resource_key',), name='uq_global_overlap_resource'),
        ),
    ]
