# Generated by Django 6.1.1 on 2026-09-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='workload_class',
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('REPORTS', 'Reports'), ('DATA_PROCESSING', 'Data Processing'), ('SYNCHRONIZATION', 'Synchronization'), ('AI_PROCESSING', 'AI Processing'), ('NOTIFICATION', 'Notification')], max_length=50),
        ),
    ]
