# Generated by Django 6.1.1 on 2026-09-12 09:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_workload_class_alter_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='idempotency_key',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=255, null=True),
        ),
    ]
