# Generated by Django 6.1.1 on 2026-09-12 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_idempotency_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='retry_policy',
        ),
        migrations.DeleteModel(
            name='RetryPolicy',
        ),
    ]
